defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
description: "Personal site"      
future: false
paginate: 6
paginate_path: 'page:num'
permalink: /:categories/:title/
theme: jekyll-theme-hacker
timezone: Europe/Kiev
title: undead404
